### ISSUE TITLE
how to work with this?

### ISSUE THREAD

**Issue by ghost** [aparwal/DeepSeparation#1]
Hi,

this seems like an interesting project and I am sure you have more commits to do before the final version. I was just wondering if you can provide a quick rundown in the Readme file perhaps on how to operate with this framework when it comes to the training part (maybe even with custom dataset?) and also the testing part, how to use a trained model on some mixture wav file and get separated wav files in directory.

Thank you very much for your time and research! :)

**Comment by aparwal** [comment]
Hey,
I just started working on it 2 days ago and the so a lot of things are still under development. Training is a bit cumbersome right now as I write even the spectogram to disk in interest of faster training of various models. However I've updated the readme so you can test the current model using stems.mp4 files. I'll write a function to use wav files soon.

**Comment by ghost** [comment]
Thank you very much! One last thing, can you just put in the Readme, what versions are needed for this in terms of Python, Keras, etc? The requirements. Thank you again!

**Comment by aparwal** [comment]
I'm planning to update the readme once I have a decent performing model. As of now, I built it using the latest versions of python, keras, SciPy and [musdb](https://github.com/sigsep/sigsep-mus-db)

**Comment by ghost** [comment]
ok, thanks a lot, can't wait to see more from this!
